[package]
name = "headson"
version = "0.0.1"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = "4.5.13"
pretty_assertions = "1.4.0"

[dev-dependencies]
assert_cmd = "2.0.15"
predicates = "3.1.2"
rand = "0.8.5"
